#!/usr/bin/env sh

# used for script output
message () {
  echo ""
  echo "==========================================================================="
  echo ""
  echo "        " "$1"
  echo ""
  echo "==========================================================================="
  echo ""
}

message "Installing dependencies with yarn..."
yarn install --frozen-lockfile || exit 1

# production build - needed for some of the subsequent checks, like storybook
message "Running production build..."
cp ./docker/.env.docker.prod ./packages/venia-concept/.env
yarn run build || exit 1

# jest tests - does not fail ci, failures are evaluated by danger check below
message "Running unit tests with Jest..."
yarn run test:ci

message "Running Coveralls..."
yarn run coveralls

message "Running Storybook..."
yarn workspace @magento/venia-concept run storybook:build || exit 1

message "Running Bundlesize..."
yarn run bundlesize

# danger ci - eslint, prettier:validate, unit test evaluation, etc.
message "Running Danger..."
yarn run danger
