#!/usr/bin/env sh

# used for script output
message () {
  echo ""
  echo "==========================================================================="
  echo ""
  echo "        " "$1"
  echo ""
  echo "==========================================================================="
  echo ""
}
STATUS=0

message "Installing dependencies with yarn..."
RUN yarn install --frozen-lockfile
#yarn install --frozen-lockfile 2>&1 || STATUS=$?

# production build - needed for some of the subsequent checks, like storybook
message "Running production build..."
cp ./docker/.env.docker.prod ./packages/venia-concept/.env
yarn run build 2>&1 || STATUS=$?
if [ $STATUS -eq 1 ]; then
   echo "yarn build failed"
   exit 1
fi

# jest tests - does not fail ci, failures are evaluated by danger check below
message "Running unit tests with Jest..."
yarn run test:ci

message "Running Coveralls..."
yarn run coveralls

message "Running Storybook..."
yarn workspace @magento/venia-concept run storybook:build

message "Running Bundlesize..."
yarn run bundlesize

# danger ci - eslint, prettier:validate, unit test evaluation, etc.
message "Running Danger..."
yarn run danger || STATUS=$?

echo "Exit Status: $STATUS"
exit $STATUS
