export const DISPLAY_MODE_FIXED_TYPE = `fixed`;
export const DYNAMIC_BLOCK_FIXED_TYPE = `SPECIFIED`;
export const DISPLAY_MODE_SALES_RULE_TYPE = `salesrule`;
export const DYNAMIC_BLOCK_SALES_RULE_TYPE = `CART_PRICE_RULE_RELATED`;
export const DISPLAY_MODE_CATALOG_RULE_TYPE = `catalogrule`;
export const DYNAMIC_BLOCK_CATALOG_RULE_TYPE = `CATALOG_PRICE_RULE_RELATED`;
